#!/bin/bash
. /var/openpanel/api/sh/module.sh

BackupAdmin.update() {
  notifyaddr=$(coreval BackupAdmin notifyaddress)
  runtime=$(coreval BackupAdmin schedule)
  authd runscript openapp-backup-cron-schedule "$runtime" "$notifyaddr"
}

Module.getconfig() {
NOTIFY_ADDR=admin@example.com
SCHEDULE=donotrun

for runtime in daily weekly monthly; do
    if [ -f /etc/cron.$runtime/openapp-backup ]; then
		SCHEDULE=$runtime
		NOTIFY_ADDR=$(grep ^NOTIFY_ADDR /etc/cron.$runtime/openapp-backup | cut -f2 -d'=')
	fi
done

  cat << _EOF_
  <openpanel.module>
    <dict id="BackupAdmin" type="class">
      <dict id="openapp-backup-settings" type="object">
	    <string id="notifyaddress">${NOTIFY_ADDR}</string>
	    <enum id="schedule">${SCHEDULE}</enum>
      </dict>
    </dict>
	<dict id="OpenCORE:Result">
      <integer id="error">0</integer>
      <string id="message">OK</string>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

BackupAdmin:Backups.listobjects() {

  cat << _EOF_
<?xml version="1.0" encoding="UTF-8"?>
<dict>
  <dict id="objects">
_EOF_

STORDIR=/var/openpanel/conf/staging/OpenAppBackup/

NRBACKUPS=$(find ${STORDIR} -type f -name openapp-backup\*.sh | wc -l)

[ $NRBACKUPS -gt 0 ] || cat << _EOF_
    <dict id="BackupAdmin:Backups" type="class">
      <dict id="There are no backups yet" type="object">
        <string id="id">There are no backups yet</string>
        <string id="date"></string>
        <string id="time"></string>
        <string id="class">BackupAdmin:Backups</string>
      </dict>
    </dict>
_EOF_

find ${STORDIR} -type f -name openapp-backup\*.sh | while read backupfile; do
    backupfile=$(echo ${backupfile##$STORDIR})    
    datestamp=$(echo ${backupfile} | cut -f2 -d_)
    timestamp=$(echo ${backupfile} | cut -f3 -d_)
    timestamp=$(echo ${timestamp%%:.sh} | sed -e 's/\([0-9]\{2\}\)/\1:/g')

    cat << _EOF_
    <dict id="BackupAdmin:Backups" type="class">
      <dict id="${backupfile}" type="object">
        <string id="id">${backupfile}</string>
        <string id="date">${datestamp}</string>
        <string id="time">${timestamp}</string>
        <string id="class">BackupAdmin:Backups</string>
      </dict>
    </dict>
_EOF_
done

  cat << _EOF_
  </dict>
  <dict id="OpenCORE:Result">
    <integer id="error">0</integer>
    <string id="message">OK</string>
  </dict>
</dict>
_EOF_
  exitquiet
}

BackupAdmin:Backups.runbackup() {
  authd runscript openapp-backup-now 
}

implement OpenAppBackup.module
