#!/bin/bash
. /var/openpanel/api/sh/module.sh

BackupAdmin.update() {
  notifyaddr=$(coreval BackupAdmin notifyaddress)
  runtime=$(coreval BackupAdmin schedule)
  authd runscript openapp-backup-cron-schedule "$runtime" "$notifyaddr"
}

Module.getconfig() {
NOTIFY_ADDR=admin@example.com
SCHEDULE=daily

for runtime in daily weekly monthly; do
    if [ -f /etc/cron.$runtime/openapp-backup ]; then
		SCHEDULE=$runtime
		NOTIFY_ADDR=$(grep ^NOTIFY_ADDR /etc/cron.$runtime/openapp-backup | cut -f2 -d'=')
	fi
done

  cat << _EOF_
  <openpanel.module>
    <dict id="BackupAdmin" type="class">
      <dict id="openapp-backup-settings" type="object">
	    <string id="notifyaddress">${NOTIFY_ADDR}</string>
	    <enum id="schedule">${SCHEDULE}</enum>
      </dict>
    </dict>
	<dict id="OpenCORE:Result">
      <integer id="error">0</integer>
      <string id="message">OK</string>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

implement OpenAppMysql.module
