#!/bin/bash

schedule=$1
notifyaddr=$2

fatal() {
    echo $1
    FATALS=$FATALS+1
    exit 1
}

[ -z $schedule ] && fatal "Not enough arguments"

if [ "$schedule" = "donotrun" ]; then
	for runtime in daily weekly monthly; do
		[ -f /etc/cron.$runtime/openapp-backup ] && rm -rf /etc/cron.$runtime/openapp-backup
	done
	exit 0
else
	[ -z ${notifyaddr} ] && fatal "Not enough arguments"
fi

TMPFILE=$(mktemp)

cat <<EOB > ${TMPFILE}
#!/bin/sh

NOTIFY_ADDR=${notifyaddr}

OUTPUT=\$(/usr/sbin/openapp-backup)
if [ \$? -gt 0 ]; then
	cat <<EOM | mail -s "Errors while running openapp-backup" \${NOTIFY_ADDR}
Something went wrong while running openapp-backup. Please see the following
output:
\${OUTPUT}
EOM
else
	FILENAME=\$(date +%F_%H%M%S)
	mv /tmp/openapp-backup.sh /var/openpanel/conf/staging/OpenAppBackup/openapp-backup_\${FILENAME}.sh
    chmod 640 /var/openpanel/conf/staging/OpenAppBackup/openapp-backup_\${FILENAME}.sh
    chown root:opencore /var/openpanel/conf/staging/OpenAppBackup/openapp-backup_\${FILENAME}.sh

	echo "\${OUTPUT}" | sed -e "s#/tmp/openapp-backup.sh#/var/openpanel/conf/staging/OpenAppBackup/openapp-backup_\${FILENAME}.sh#" | mail -s "Your openapp-backup output" \${NOTIFY_ADDR}
fi
EOB

for runtime in daily weekly monthly; do
    [ -f /etc/cron.$runtime/openapp-backup ] && rm -rf /etc/cron.$runtime/openapp-backup
done

mv ${TMPFILE} /etc/cron.$schedule/openapp-backup
chmod +x /etc/cron.$schedule/openapp-backup
