#!/bin/bash

notifyaddr= $1
schedule= $2

fatal() {
    echo $1
    FATALS=$FATALS+1
    exit 1
}

[ -z $2 -o $1 ] && fatal "Not enough arguments"

TMPFILE=$(mktemp)

cat <<EOB > ${TMPFILE}
/usr/sbin/openapp-backup | mail -s "Your openapp-backup output" ${notifyaddr}
EOB

for runtime in daily weekly monthly; do
    [ -f /etc/cron.$runtime/openapp-backup ] && rm -rf /etc/cron.$runtime/openapp-backup
done

mv ${TMPFILE} /etc/cron.$schedule/openapp-backup
